# Generated by Django 4.0.5 on 2024-03-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell', models.IntegerField()),
                ('code', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
