# Generated by Django 4.0.5 on 2024-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cell',
            name='code',
            field=models.TextField(),
        ),
    ]
